package id.segari.service.common;

public enum InternalResponseCode {
    SUCCESS,
    BASIC,
    NOT_FOUND,
    INVALID_ARGUMENT,
    VALIDATION_ERROR,
    INTERNAL_ERROR,
    INIT_CONTEXT_FAILED,
    USB_DEVICE_NOT_FOUND,
    UNABLE_TO_DETACH_KERNEL_DRIVER,
    UNABLE_TO_CLAIM_INTERFACE,
    PRINTER_ALREADY_CONNECTED,
    SUCCESS_CONNECTING_PRINTER,
    CANNOT_FIND_CONNECTED_PRINTER,
    SUCCESS_DISCONNECTING_PRINTER,
    UNABLE_TO_GET_DEVICE_LIST,
    FAILED_TO_PRINT, WEBSOCKET_EMPTY_CONFIG, INVALID_WAREHOUSE_ID, WEBSOCKET_ALLOW_ONLY_ONE_WAREHOUSE, WEBSOCKET_WAREHOUSE_NOT_CONNECTED, WEBSOCKET_CONNECTION_FAILED, PRINT_QUEUE_MAX_QUEUE, PRINT_QUEUE_MAX_JOB, UPDATE_ERROR;
}
