package id.segari.printer.segariprintermiddleware.common;

public enum InternalResponseCode {
    SUCCESS,
    BASIC,
    NOT_FOUND,
    INVALID_ARGUMENT,
    INTERNAL_ERROR,
    INIT_CONTEXT_FAILED,
    USB_DEVICE_NOT_FOUND,
    UNABLE_TO_DETACH_KERNEL_DRIVER,
    UNABLE_TO_CLAIM_INTERFACE,
    PRINTER_ALREADY_CONNECTED,
    SUCCESS_CONNECTING_PRINTER,
    CANNOT_FIND_CONNECTED_PRINTER,
    SUCCESS_DISCONNECTING_PRINTER,
    UNABLE_TO_GET_DEVICE_LIST,
    FAILED_TO_PRINT;
}
